# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: agentPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
  displayName: 'Checkout source'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      cd flask-sklearn
      make all
      az webapp up --name fl-app -g Azuredevops --sku B1
      Write-Host "Hello World"
  displayName: 'Deploy FL app'
