# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: agentPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
  displayName: 'Checkout source'

- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    azureSubscription: arm
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      cd flask-sklearn
      make all

- task: AzureCLI@2
  inputs:
    azureSubscription: 'arm'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd flask-sklearn
      az webapp up --name fl-app -g Azuredevops --sku B1 --logs --runtime "PYTHON:3.9"
  displayName: 'Deploy FL app'
