# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: agentPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    cd flask-sklearn
    make all
    az webapp up --name fl-app -g Azuredevops --sku B1 --logs --runtime "PYTHON:3.9"
    
  displayName: 'Deploy FL app'
